### ISSUE TITLE
Owned games can't be (re)loaded

### ISSUE THREAD

**Issue by pizzahut2** [RedSparr0w/IndieGala-Helper#25]
Even with public profile, in both Chrome and Firefox, this error occurs:

Something went wrong when updating your owned games list.
{"readyState":0,"status":0,"statusText":"error"}

**Comment by Kureka** [comment]
It's because this extension try to access https://api.enhancedsteam.com/steamapi/GetOwnedGames but enhanced steam API already dead.

**Comment by RedSparr0w** [comment]
Thanks for looking into this @Kureka 😄 
I'll try fixing this in the next week or so.

**Comment by RedSparr0w** [comment]
Should be fixed in latest release! `v4.6.2`

**Comment by pizzahut2** [comment]
Still not in the Mozilla store. I hope they approve it soon.

**Comment by pizzahut2** [comment]
On AMO there's still the old version v4.5.2 from 2018. Did they deny approval or is it somehow stuck, waiting for approval?

**Comment by pizzahut2** [comment]
@RedSparr0w On AMO there's still the old version v4.5.2 from 2018. Did they deny approval or is it somehow stuck, waiting for approval?
